### ISSUE TITLE
Gevent update breaks player

### ISSUE THREAD

**Issue by govg** [jonian/acestream-proxy-player#2]
http://www.gevent.org/whatsnew_1_0.html - The new Gevent module deprecates the gevent.coros module. As a result, executing acestreamproxy-player streamlink gives an error, namely that gevent.coros was not found when executing from vlcclient/vlcclient.py.

**Comment by govg** [comment]
The bug seems to originate from acestream-proxy, and not this package. Please mark acestream-proxy as a required package in the AUR (it is currently marked as option), I will open the issue in the relevant repository. Thank you.

**Comment by jonian** [comment]
The acestream-proxy package is marked as optional because acestream-proxy-player can also work with acestream-proxy installed in a remote server.

**Comment by govg** [comment]
Yes, I had noticed that earlier. Sorry for the trouble!

**Comment by jonian** [comment]
No trouble. Thank you for your input.
